---

- hosts: all
  become: true
  # if using ansible-vault
  #vars_files:
  #  - my_vault.yml

  tasks:
# tasks file for ansible-role-ai

  - name: Install packages
    import_tasks: packages.yml
    become: yes

  - name: Harden XRDP
    import_tasks: xrdp_hardening.yml
    become: yes

  - name: Create local user for XRDP
    import_tasks: local_rdp_user.yml
    become: yes
